evaluationDependsOn(':')

java {
    sourceCompatibility = JavaVersion.VERSION_1_8
    targetCompatibility = JavaVersion.VERSION_1_8
}

ext {
    oldServletApiTargetVersion = '2.3'
    oldMortbayJettyVersion = '6.1.7'
}

dependencies {
    testImplementation(
            project(":wingtips-servlet-api"),
            "org.junit.jupiter:junit-jupiter:$junitJupiterVersion",
            "org.mockito:mockito-core:$mockitoVersion",
            "ch.qos.logback:logback-classic:$logbackVersion",
            "org.assertj:assertj-core:$assertJVersion",
            "io.rest-assured:rest-assured:$restAssuredVersion",
            "javax.servlet:servlet-api:$oldServletApiTargetVersion",
            "org.mortbay.jetty:jetty:$oldMortbayJettyVersion",
            // The jaxb-api is needed for building on the java 11 JDK as these classes were moved out of the Java SE libs.
            "javax.xml.bind:jaxb-api:$jaxbApiVersion",
    )
    testRuntimeOnly("org.junit.platform:junit-platform-launcher:$junitPlatformVersion")
}
