evaluationDependsOn(':')

compileTestJava {
    sourceCompatibility = JavaVersion.VERSION_1_8
    targetCompatibility = JavaVersion.VERSION_1_8
}

dependencies {
    api(
            project(":wingtips-core"),
            "com.lightstep.tracer:lightstep-tracer-jre:$lightstepTracerVersion",
            "com.lightstep.tracer:tracer-okhttp:$lightstepHttpVersion",
            "io.grpc:grpc-netty:$grpcNettyVersion",
            "io.netty:netty-tcnative-boringssl-static:$nettyTcnativeBoringVersion",
            "commons-codec:commons-codec:$apacheCommonsCodecVersion",
    )
    compileOnly(
            "org.jetbrains:annotations:$jetbrainsAnnotationsVersion"
    )
    testImplementation(
            "org.jetbrains:annotations:$jetbrainsAnnotationsVersion",
            "org.junit.jupiter:junit-jupiter:$junitJupiterVersion",
            "org.mockito:mockito-core:$mockitoVersion",
            "org.assertj:assertj-core:$assertJVersion",
            "ch.qos.logback:logback-classic:$logbackVersion",
    )
    testRuntimeOnly("org.junit.platform:junit-platform-launcher:$junitPlatformVersion")
}
