evaluationDependsOn(':')

java {
    sourceCompatibility = JavaVersion.VERSION_1_8
    targetCompatibility = JavaVersion.VERSION_1_8
}

ext {
    // This should match the version of Project Reactor pulled in by whatever springboot2Version is using.
    projectReactorVersion = '3.4.34'
}

dependencies {
    api(
            project(":wingtips-core"),
            project(":wingtips-java8")
    )
    compileOnly(
            "org.springframework:spring-webflux:$spring5Version",
            "org.jetbrains:annotations:$jetbrainsAnnotationsVersion",
    )
    testImplementation(
            "org.junit.jupiter:junit-jupiter:$junitJupiterVersion",
            "org.mockito:mockito-core:$mockitoVersion",
            "org.assertj:assertj-core:$assertJVersion",
            "io.rest-assured:rest-assured:$restAssuredVersion",
            "org.jetbrains:annotations:$jetbrainsAnnotationsVersion",
            "ch.qos.logback:logback-classic:$logbackVersion",
            "org.springframework.boot:spring-boot-starter-webflux:$springboot2Version",
            "io.projectreactor:reactor-test:$projectReactorVersion",
            // The jaxb-api is needed for building on the java 11 JDK as these classes were moved out of the Java SE libs.
            "javax.xml.bind:jaxb-api:$jaxbApiVersion",
    )
    testRuntimeOnly("org.junit.platform:junit-platform-launcher:$junitPlatformVersion")
}
